# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/murt/Programs/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/murt/Programs/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/murt/GitHub/Pacman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/murt/GitHub/Pacman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/murt/Programs/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/murt/Programs/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/murt/GitHub/Pacman/CMakeFiles /home/murt/GitHub/Pacman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/murt/GitHub/Pacman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pacman_server

# Build rule for target.
pacman_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pacman_server
.PHONY : pacman_server

# fast build rule for target.
pacman_server/fast:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/build
.PHONY : pacman_server/fast

#=============================================================================
# Target rules for targets named pacman

# Build rule for target.
pacman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pacman
.PHONY : pacman

# fast build rule for target.
pacman/fast:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/build
.PHONY : pacman/fast

Client/BeingView.o: Client/BeingView.cpp.o

.PHONY : Client/BeingView.o

# target to build an object file
Client/BeingView.cpp.o:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/BeingView.cpp.o
.PHONY : Client/BeingView.cpp.o

Client/BeingView.i: Client/BeingView.cpp.i

.PHONY : Client/BeingView.i

# target to preprocess a source file
Client/BeingView.cpp.i:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/BeingView.cpp.i
.PHONY : Client/BeingView.cpp.i

Client/BeingView.s: Client/BeingView.cpp.s

.PHONY : Client/BeingView.s

# target to generate assembly for a file
Client/BeingView.cpp.s:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/BeingView.cpp.s
.PHONY : Client/BeingView.cpp.s

Client/Factory.o: Client/Factory.cpp.o

.PHONY : Client/Factory.o

# target to build an object file
Client/Factory.cpp.o:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/Factory.cpp.o
.PHONY : Client/Factory.cpp.o

Client/Factory.i: Client/Factory.cpp.i

.PHONY : Client/Factory.i

# target to preprocess a source file
Client/Factory.cpp.i:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/Factory.cpp.i
.PHONY : Client/Factory.cpp.i

Client/Factory.s: Client/Factory.cpp.s

.PHONY : Client/Factory.s

# target to generate assembly for a file
Client/Factory.cpp.s:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/Factory.cpp.s
.PHONY : Client/Factory.cpp.s

Client/GameLoop.o: Client/GameLoop.cpp.o

.PHONY : Client/GameLoop.o

# target to build an object file
Client/GameLoop.cpp.o:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/GameLoop.cpp.o
.PHONY : Client/GameLoop.cpp.o

Client/GameLoop.i: Client/GameLoop.cpp.i

.PHONY : Client/GameLoop.i

# target to preprocess a source file
Client/GameLoop.cpp.i:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/GameLoop.cpp.i
.PHONY : Client/GameLoop.cpp.i

Client/GameLoop.s: Client/GameLoop.cpp.s

.PHONY : Client/GameLoop.s

# target to generate assembly for a file
Client/GameLoop.cpp.s:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/GameLoop.cpp.s
.PHONY : Client/GameLoop.cpp.s

Client/Ghost.o: Client/Ghost.cpp.o

.PHONY : Client/Ghost.o

# target to build an object file
Client/Ghost.cpp.o:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/Ghost.cpp.o
.PHONY : Client/Ghost.cpp.o

Client/Ghost.i: Client/Ghost.cpp.i

.PHONY : Client/Ghost.i

# target to preprocess a source file
Client/Ghost.cpp.i:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/Ghost.cpp.i
.PHONY : Client/Ghost.cpp.i

Client/Ghost.s: Client/Ghost.cpp.s

.PHONY : Client/Ghost.s

# target to generate assembly for a file
Client/Ghost.cpp.s:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/Ghost.cpp.s
.PHONY : Client/Ghost.cpp.s

Client/Pacman.o: Client/Pacman.cpp.o

.PHONY : Client/Pacman.o

# target to build an object file
Client/Pacman.cpp.o:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/Pacman.cpp.o
.PHONY : Client/Pacman.cpp.o

Client/Pacman.i: Client/Pacman.cpp.i

.PHONY : Client/Pacman.i

# target to preprocess a source file
Client/Pacman.cpp.i:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/Pacman.cpp.i
.PHONY : Client/Pacman.cpp.i

Client/Pacman.s: Client/Pacman.cpp.s

.PHONY : Client/Pacman.s

# target to generate assembly for a file
Client/Pacman.cpp.s:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/Pacman.cpp.s
.PHONY : Client/Pacman.cpp.s

Client/PlayerConnectionClient.o: Client/PlayerConnectionClient.cpp.o

.PHONY : Client/PlayerConnectionClient.o

# target to build an object file
Client/PlayerConnectionClient.cpp.o:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/PlayerConnectionClient.cpp.o
.PHONY : Client/PlayerConnectionClient.cpp.o

Client/PlayerConnectionClient.i: Client/PlayerConnectionClient.cpp.i

.PHONY : Client/PlayerConnectionClient.i

# target to preprocess a source file
Client/PlayerConnectionClient.cpp.i:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/PlayerConnectionClient.cpp.i
.PHONY : Client/PlayerConnectionClient.cpp.i

Client/PlayerConnectionClient.s: Client/PlayerConnectionClient.cpp.s

.PHONY : Client/PlayerConnectionClient.s

# target to generate assembly for a file
Client/PlayerConnectionClient.cpp.s:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/PlayerConnectionClient.cpp.s
.PHONY : Client/PlayerConnectionClient.cpp.s

Client/TileMap.o: Client/TileMap.cpp.o

.PHONY : Client/TileMap.o

# target to build an object file
Client/TileMap.cpp.o:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/TileMap.cpp.o
.PHONY : Client/TileMap.cpp.o

Client/TileMap.i: Client/TileMap.cpp.i

.PHONY : Client/TileMap.i

# target to preprocess a source file
Client/TileMap.cpp.i:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/TileMap.cpp.i
.PHONY : Client/TileMap.cpp.i

Client/TileMap.s: Client/TileMap.cpp.s

.PHONY : Client/TileMap.s

# target to generate assembly for a file
Client/TileMap.cpp.s:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/TileMap.cpp.s
.PHONY : Client/TileMap.cpp.s

Client/main.o: Client/main.cpp.o

.PHONY : Client/main.o

# target to build an object file
Client/main.cpp.o:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/main.cpp.o
.PHONY : Client/main.cpp.o

Client/main.i: Client/main.cpp.i

.PHONY : Client/main.i

# target to preprocess a source file
Client/main.cpp.i:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/main.cpp.i
.PHONY : Client/main.cpp.i

Client/main.s: Client/main.cpp.s

.PHONY : Client/main.s

# target to generate assembly for a file
Client/main.cpp.s:
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/Client/main.cpp.s
.PHONY : Client/main.cpp.s

Server/BaseBeing.o: Server/BaseBeing.cpp.o

.PHONY : Server/BaseBeing.o

# target to build an object file
Server/BaseBeing.cpp.o:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/BaseBeing.cpp.o
.PHONY : Server/BaseBeing.cpp.o

Server/BaseBeing.i: Server/BaseBeing.cpp.i

.PHONY : Server/BaseBeing.i

# target to preprocess a source file
Server/BaseBeing.cpp.i:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/BaseBeing.cpp.i
.PHONY : Server/BaseBeing.cpp.i

Server/BaseBeing.s: Server/BaseBeing.cpp.s

.PHONY : Server/BaseBeing.s

# target to generate assembly for a file
Server/BaseBeing.cpp.s:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/BaseBeing.cpp.s
.PHONY : Server/BaseBeing.cpp.s

Server/Ghost.o: Server/Ghost.cpp.o

.PHONY : Server/Ghost.o

# target to build an object file
Server/Ghost.cpp.o:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/Ghost.cpp.o
.PHONY : Server/Ghost.cpp.o

Server/Ghost.i: Server/Ghost.cpp.i

.PHONY : Server/Ghost.i

# target to preprocess a source file
Server/Ghost.cpp.i:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/Ghost.cpp.i
.PHONY : Server/Ghost.cpp.i

Server/Ghost.s: Server/Ghost.cpp.s

.PHONY : Server/Ghost.s

# target to generate assembly for a file
Server/Ghost.cpp.s:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/Ghost.cpp.s
.PHONY : Server/Ghost.cpp.s

Server/MapManager.o: Server/MapManager.cpp.o

.PHONY : Server/MapManager.o

# target to build an object file
Server/MapManager.cpp.o:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/MapManager.cpp.o
.PHONY : Server/MapManager.cpp.o

Server/MapManager.i: Server/MapManager.cpp.i

.PHONY : Server/MapManager.i

# target to preprocess a source file
Server/MapManager.cpp.i:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/MapManager.cpp.i
.PHONY : Server/MapManager.cpp.i

Server/MapManager.s: Server/MapManager.cpp.s

.PHONY : Server/MapManager.s

# target to generate assembly for a file
Server/MapManager.cpp.s:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/MapManager.cpp.s
.PHONY : Server/MapManager.cpp.s

Server/Pacman.o: Server/Pacman.cpp.o

.PHONY : Server/Pacman.o

# target to build an object file
Server/Pacman.cpp.o:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/Pacman.cpp.o
.PHONY : Server/Pacman.cpp.o

Server/Pacman.i: Server/Pacman.cpp.i

.PHONY : Server/Pacman.i

# target to preprocess a source file
Server/Pacman.cpp.i:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/Pacman.cpp.i
.PHONY : Server/Pacman.cpp.i

Server/Pacman.s: Server/Pacman.cpp.s

.PHONY : Server/Pacman.s

# target to generate assembly for a file
Server/Pacman.cpp.s:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/Pacman.cpp.s
.PHONY : Server/Pacman.cpp.s

Server/PlayerConnectionServer.o: Server/PlayerConnectionServer.cpp.o

.PHONY : Server/PlayerConnectionServer.o

# target to build an object file
Server/PlayerConnectionServer.cpp.o:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/PlayerConnectionServer.cpp.o
.PHONY : Server/PlayerConnectionServer.cpp.o

Server/PlayerConnectionServer.i: Server/PlayerConnectionServer.cpp.i

.PHONY : Server/PlayerConnectionServer.i

# target to preprocess a source file
Server/PlayerConnectionServer.cpp.i:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/PlayerConnectionServer.cpp.i
.PHONY : Server/PlayerConnectionServer.cpp.i

Server/PlayerConnectionServer.s: Server/PlayerConnectionServer.cpp.s

.PHONY : Server/PlayerConnectionServer.s

# target to generate assembly for a file
Server/PlayerConnectionServer.cpp.s:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/PlayerConnectionServer.cpp.s
.PHONY : Server/PlayerConnectionServer.cpp.s

Server/main.o: Server/main.cpp.o

.PHONY : Server/main.o

# target to build an object file
Server/main.cpp.o:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/main.cpp.o
.PHONY : Server/main.cpp.o

Server/main.i: Server/main.cpp.i

.PHONY : Server/main.i

# target to preprocess a source file
Server/main.cpp.i:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/main.cpp.i
.PHONY : Server/main.cpp.i

Server/main.s: Server/main.cpp.s

.PHONY : Server/main.s

# target to generate assembly for a file
Server/main.cpp.s:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/Server/main.cpp.s
.PHONY : Server/main.cpp.s

generated/service.grpc.pb.o: generated/service.grpc.pb.cc.o

.PHONY : generated/service.grpc.pb.o

# target to build an object file
generated/service.grpc.pb.cc.o:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/generated/service.grpc.pb.cc.o
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/generated/service.grpc.pb.cc.o
.PHONY : generated/service.grpc.pb.cc.o

generated/service.grpc.pb.i: generated/service.grpc.pb.cc.i

.PHONY : generated/service.grpc.pb.i

# target to preprocess a source file
generated/service.grpc.pb.cc.i:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/generated/service.grpc.pb.cc.i
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/generated/service.grpc.pb.cc.i
.PHONY : generated/service.grpc.pb.cc.i

generated/service.grpc.pb.s: generated/service.grpc.pb.cc.s

.PHONY : generated/service.grpc.pb.s

# target to generate assembly for a file
generated/service.grpc.pb.cc.s:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/generated/service.grpc.pb.cc.s
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/generated/service.grpc.pb.cc.s
.PHONY : generated/service.grpc.pb.cc.s

generated/service.pb.o: generated/service.pb.cc.o

.PHONY : generated/service.pb.o

# target to build an object file
generated/service.pb.cc.o:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/generated/service.pb.cc.o
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/generated/service.pb.cc.o
.PHONY : generated/service.pb.cc.o

generated/service.pb.i: generated/service.pb.cc.i

.PHONY : generated/service.pb.i

# target to preprocess a source file
generated/service.pb.cc.i:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/generated/service.pb.cc.i
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/generated/service.pb.cc.i
.PHONY : generated/service.pb.cc.i

generated/service.pb.s: generated/service.pb.cc.s

.PHONY : generated/service.pb.s

# target to generate assembly for a file
generated/service.pb.cc.s:
	$(MAKE) -f CMakeFiles/pacman_server.dir/build.make CMakeFiles/pacman_server.dir/generated/service.pb.cc.s
	$(MAKE) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/generated/service.pb.cc.s
.PHONY : generated/service.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pacman_server"
	@echo "... pacman"
	@echo "... Client/BeingView.o"
	@echo "... Client/BeingView.i"
	@echo "... Client/BeingView.s"
	@echo "... Client/Factory.o"
	@echo "... Client/Factory.i"
	@echo "... Client/Factory.s"
	@echo "... Client/GameLoop.o"
	@echo "... Client/GameLoop.i"
	@echo "... Client/GameLoop.s"
	@echo "... Client/Ghost.o"
	@echo "... Client/Ghost.i"
	@echo "... Client/Ghost.s"
	@echo "... Client/Pacman.o"
	@echo "... Client/Pacman.i"
	@echo "... Client/Pacman.s"
	@echo "... Client/PlayerConnectionClient.o"
	@echo "... Client/PlayerConnectionClient.i"
	@echo "... Client/PlayerConnectionClient.s"
	@echo "... Client/TileMap.o"
	@echo "... Client/TileMap.i"
	@echo "... Client/TileMap.s"
	@echo "... Client/main.o"
	@echo "... Client/main.i"
	@echo "... Client/main.s"
	@echo "... Server/BaseBeing.o"
	@echo "... Server/BaseBeing.i"
	@echo "... Server/BaseBeing.s"
	@echo "... Server/Ghost.o"
	@echo "... Server/Ghost.i"
	@echo "... Server/Ghost.s"
	@echo "... Server/MapManager.o"
	@echo "... Server/MapManager.i"
	@echo "... Server/MapManager.s"
	@echo "... Server/Pacman.o"
	@echo "... Server/Pacman.i"
	@echo "... Server/Pacman.s"
	@echo "... Server/PlayerConnectionServer.o"
	@echo "... Server/PlayerConnectionServer.i"
	@echo "... Server/PlayerConnectionServer.s"
	@echo "... Server/main.o"
	@echo "... Server/main.i"
	@echo "... Server/main.s"
	@echo "... generated/service.grpc.pb.o"
	@echo "... generated/service.grpc.pb.i"
	@echo "... generated/service.grpc.pb.s"
	@echo "... generated/service.pb.o"
	@echo "... generated/service.pb.i"
	@echo "... generated/service.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

